/*
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 * SPDX-License-Identifier: EUPL-1.2
 *
 * Regression e2e for the parts of Portaliq that are NOT the public portal:
 * the internal Vue admin SPA (`/apps/portaliq/…`, bundle `portaliq-main.js`),
 * the Nextcloud admin settings section, and the three HTTP contracts an
 * operator touches — `/api/settings`, `/api/metrics`, `/api/health`.
 *
 * WHY A SECOND SHAPE OF SPEC IN THIS SUITE
 * ----------------------------------------
 * Every pre-existing spec here drives the PUBLIC portal (`portaliq-portal.js`)
 * and authenticates itself through the debug-gated portal bearer edge. None of
 * them ever logs into Nextcloud, so nothing in this suite had ever rendered the
 * admin SPA or opened `/settings/admin/portaliq` — the `dashboard-page`,
 * `admin-ui`, `settings-management` and `observability` capabilities were
 * entirely unexercised end-to-end (hydra gate-19), and `src/views/
 * FeaturesRoadmap.vue` had no e2e reference at all (gate-26).
 *
 * TWO IDENTITIES, TWO COOKIE JARS — THIS IS LOAD-BEARING
 * ------------------------------------------------------
 * Several assertions below are *negative*: a non-admin, or an anonymous
 * caller, must NOT be able to read metrics or write settings.
 *
 * The precise rule, measured rather than assumed, because two half-truths
 * about it contradicted each other for a while:
 *
 *   - a VALID session cookie OUTRANKS a later Basic header. Nextcloud
 *     resolves the cookie first, so a context that authenticated as admin and
 *     then "switches" identity by sending different Basic credentials KEEPS
 *     RUNNING AS ADMIN. A per-request Authorization header is not an identity
 *     switch.
 *   - a STALE cookie authenticates nobody — the request comes back as
 *     unauthenticated rather than as its former owner.
 *
 * Only the first case matters here, and it is the dangerous one: it turns
 * "403 for a non-admin" into a silent 200, filing an authorization hole that
 * does not exist — or hiding one that does. The consequence is that identity
 * must be separated AT THE JAR, not at the request: Playwright's built-in
 * `request` fixture is ONE context for the whole test, so it is deliberately
 * not used for the identity-sensitive calls.
 * `newIdentity()` below mints a fresh, isolated jar per identity, and
 * `assertCallerIs()` proves — in the same chain, against `/ocs/v2.php/cloud/
 * user` — that the request really is being made by the identity the assertion
 * names. Without that proof a green negative test says nothing.
 *
 * WHAT THIS SPEC ASSUMES THE INSTANCE HAS
 * ---------------------------------------
 * `tests/e2e/ci-seed.sh` (the workflow's `playwright-seed-command`) provisions
 * it and VERIFIES each piece, so a missing precondition fails loudly there
 * rather than as a selector timeout here:
 *   - the `portaliq` register + its nine schemas, and the seed `portalPage` rows
 *   - the `portaliq/jwt_signing_secret` generated by the InitializeSettings
 *     repair step (verified, never generated)
 *   - a NON-ADMIN Nextcloud user (`E2E_USER` / `E2E_PASS` below), added by the
 *     seed script for the negative assertions in this file
 *
 * @spec openspec/specs/dashboard-page/spec.md#REQ-DASH-001
 * @spec openspec/specs/dashboard-page/spec.md#REQ-DASH-002
 * @spec openspec/specs/admin-ui/spec.md#REQ-UI-001
 * @spec openspec/specs/admin-ui/spec.md#REQ-UI-002
 * @spec openspec/specs/settings-management/spec.md#REQ-CFG-001
 * @spec openspec/specs/settings-management/spec.md#REQ-CFG-002
 * @spec openspec/specs/settings-management/spec.md#REQ-CFG-003
 * @spec openspec/specs/settings-management/spec.md#REQ-CFG-004
 * @spec openspec/specs/observability/spec.md#REQ-OBS-001
 * @spec openspec/specs/observability/spec.md#REQ-OBS-002
 */

import {
	test,
	expect,
	request as playwrightRequest,
	type APIRequestContext,
	type Page,
} from '@playwright/test'

import { BASE_URL } from './base-url'

/** Nextcloud admin, as exported by the shared quality.yml Playwright step. */
const ADMIN_USER = process.env.ADMIN_USER ?? process.env.NC_ADMIN_USER ?? 'admin'
const ADMIN_PASS = process.env.ADMIN_PASSWORD ?? process.env.NC_ADMIN_PASS ?? 'admin'

/**
 * The non-admin identity provisioned by tests/e2e/ci-seed.sh.
 *
 * Kept in sync with that script by name, not by import — a bash script cannot
 * be imported. The password is >= 10 characters on purpose: Nextcloud's
 * default password policy rejects shorter ones and `occ user:add` reports that
 * rejection in a way that is easy to miss, so the seed script verifies the
 * user exists afterwards rather than trusting the add.
 */
const E2E_USER = process.env.PORTALIQ_E2E_USER ?? 'e2e-reader'
const E2E_PASS = process.env.PORTALIQ_E2E_PASS ?? 'e2e-reader-pw-2026'

const APP_BASE = '/index.php/apps/portaliq'
const API_BASE = `${APP_BASE}/api`

/** Anonymous marker for `newIdentity()`. */
type Identity = { user: string; pass: string } | 'anonymous'

/**
 * A fresh APIRequestContext with its own cookie jar.
 *
 * One per identity, never shared. See the header note: reusing a jar makes
 * every later request run as whoever authenticated last.
 *
 * @param identity The credentials to send, or 'anonymous' for none.
 * @return an isolated request context; the caller disposes it.
 */
async function newIdentity(identity: Identity): Promise<APIRequestContext> {
	const headers: Record<string, string> = {
		// Nextcloud's Request::passesCSRFCheck() short-circuits on this header.
		// A Basic-auth request carries no session cookie, so the strict-cookie
		// precondition holds and the write verbs below are not rejected as CSRF
		// failures. Without it, POST/PUT /api/settings answers 412.
		'OCS-APIRequest': 'true',
		Accept: 'application/json',
	}
	if (identity !== 'anonymous') {
		const basic = Buffer.from(`${identity.user}:${identity.pass}`).toString(
			'base64',
		)
		headers.Authorization = `Basic ${basic}`
	}
	return playwrightRequest.newContext({
		baseURL: BASE_URL,
		extraHTTPHeaders: headers,
		// AN EMPTY JAR IS ASKED FOR EXPLICITLY, even though this project does
		// not currently declare `use.storageState`.
		//
		// A context created without naming `storageState` INHERITS the
		// project's default one. This suite has no globalSetup today (see the
		// header of tests/e2e/playwright.config.ts, which says so
		// deliberately), so the default is empty and this line changes
		// nothing — today. The moment anyone adds a globalSetup that logs in,
		// every context here silently starts holding that session cookie, and
		// because a valid cookie outranks a later Authorization header, the
		// "anonymous" and "non-admin" contexts below would quietly become the
		// admin while still passing.
		//
		// That is not hypothetical: the byte-identical helper in pipelinq,
		// whose config DOES set `use.storageState`, had exactly this defect —
		// `assertCallerIs(anon, null)` read back `"admin"`. One line of
		// difference in a config file, in another repository, decided whether
		// five negative assertions meant anything.
		storageState: { cookies: [], origins: [] },
	})
}

/**
 * Prove, in the same request chain, WHO the server thinks is calling.
 *
 * The negative assertions in this file are only worth their green if the
 * caller is who the test says. `/ocs/v2.php/cloud/user` answers with the
 * resolved session identity, so it measures the same thing the endpoint under
 * test measures.
 *
 * @param ctx      The context to interrogate.
 * @param expected The uid expected, or null for "must not be authenticated".
 */
async function assertCallerIs(
	ctx: APIRequestContext,
	expected: string | null,
): Promise<void> {
	const res = await ctx.get('/ocs/v2.php/cloud/user?format=json')
	const body = await res.json().catch(() => null)
	// READ THE IDENTITY, NOT THE HTTP STATUS.
	//
	// The OCS layer reports "not logged in" as **HTTP 200** with
	// `ocs.meta.statuscode: 997` — it does not 401. The previous version of
	// this helper asserted `status !== 200` for the anonymous case, which made
	// the guard's verdict a property of how this Nextcloud version chooses to
	// signal the refusal rather than of who is actually calling. It passed
	// here and failed on pipelinq's CI against a context that was correctly
	// anonymous: the same assertion, two answers, so at most one of them was
	// measuring the thing it named.
	//
	// `ocs.data.id` is the resolved identity itself. Absent means nobody is
	// authenticated, whichever way the server says so; present means somebody
	// is, and names them. That also makes this a DISCRIMINATOR rather than a
	// smoke test: if a session cookie ever did leak into a context meant to be
	// anonymous, this reads back `admin` and fails — which is precisely the
	// failure the guard exists to catch, and which a status check cannot
	// distinguish from a version difference.
	const uid = body?.ocs?.data?.id ?? null

	if (expected === null) {
		expect(
			uid,
			'an anonymous context must not resolve to a Nextcloud user — if it does, a cookie leaked in from another identity and every negative assertion below is meaningless',
		).toBeNull()
		return
	}
	expect(
		uid,
		`this context must be acting as ${expected}; a different uid (or none) means the cookie jar is shared, or the credentials did not authenticate, and the assertions below measure the wrong caller`,
	).toBe(expected)
}

/**
 * Log into Nextcloud through the real login form.
 *
 * Deliberately per-test rather than a `globalSetup` + `storageState`: this
 * suite's config declares no storage state on purpose (see the header of
 * tests/e2e/playwright.config.ts), and adding one would change the starting
 * context of every existing portal spec.
 *
 * @param page The page to authenticate.
 * @param user Username.
 * @param pass Password.
 */
async function loginToNextcloud(
	page: Page,
	user: string,
	pass: string,
): Promise<void> {
	await page.goto('/index.php/login')
	await page.locator('input[name="user"]').fill(user)
	await page.locator('input[name="password"]').fill(pass)
	await page.locator('button[type="submit"], input[type="submit"]').first().click()
	// The global header renders only on authenticated pages.
	await page.waitForSelector('#header, header.header', { timeout: 60_000 })
	expect(
		/\/login(\?|$|\/)/.test(page.url()),
		`login as ${user} failed — still on ${page.url()}`,
	).toBe(false)
}

test.describe('admin SPA + admin settings + operator contracts', () => {
	// The catch-all route and the app root both render the same Twig `index`
	// template, and the Vue bundle mounts into `#content`. Requiring a CHILD of
	// `#content` is what makes this a MOUNT assertion instead of an HTTP one:
	// the template ships `<div id="content"></div>` whether or not the bundle
	// loads, so `#content` alone is present even when the SPA is dead.
	//
	// @e2e dashboard-page::authenticated-user-opens-the-dashboard
	test('a signed-in user opens the dashboard and the SPA mounts', async ({
		page,
	}) => {
		await loginToNextcloud(page, ADMIN_USER, ADMIN_PASS)

		const response = await page.goto(`${APP_BASE}/`)
		expect(response?.status(), 'the app root must be served').toBe(200)
		await expect(page.locator('#content > *').first()).toBeVisible({
			timeout: 60_000,
		})
	})

	// A deep link is the catch-all route's whole purpose: the server must
	// return the SAME SPA shell for a sub-path it knows nothing about, and the
	// Vue router must then resolve that path client-side. `/features-roadmap`
	// is a real manifest page (`src/manifest.json` → id `FeaturesRoadmap`,
	// route `/features-roadmap`, surfaced from the nav's footer section), so
	// this also gives `src/views/FeaturesRoadmap.vue` the e2e reference hydra
	// gate-26 asks for — and it asks for it because a page nobody ever renders
	// is a page nobody notices breaking.
	//
	// The URL assertion is the load-bearing half. If the catch-all were absent
	// the server would 404; if the Vue router's history base were wrong the
	// catch-all redirect (`/:pathMatch(.*)*` → `/`) would silently rewrite the
	// address bar back to the app root, which is exactly the failure mode
	// vue-router 4 introduced when it removed the bare `path: '*'` glob.
	//
	// @e2e dashboard-page::deep-link-to-an-in-app-route
	test('a deep link to /features-roadmap renders FeaturesRoadmap and the router keeps the path', async ({
		page,
	}) => {
		await loginToNextcloud(page, ADMIN_USER, ADMIN_PASS)

		const response = await page.goto(`${APP_BASE}/features-roadmap`)
		expect(
			response?.status(),
			'the catch-all route must serve the SPA for an in-app sub-path',
		).toBe(200)

		await expect(page.locator('#content > *').first()).toBeVisible({
			timeout: 60_000,
		})
		await expect(page).toHaveURL(/\/features-roadmap$/)

		// The URL and a non-empty #content are BOTH satisfied by the app shell
		// alone — the catch-all could resolve to a blank view and this test
		// would still pass. So assert the view put its OWN heading on screen.
		//
		// `Features` is the page's h2, read off the rendered page rather than
		// guessed; the h3 below it is prose and would make a brittle anchor.
		//
		// This is also the reference gate-26 asks for. `FeaturesRoadmap` had
		// only ever appeared in this file's COMMENTS, and the gate reads
		// EXECUTABLE text — a mention is not coverage, which is exactly the
		// distinction the gate exists to draw.
		await expect(
			page.getByRole('heading', { name: 'Features', exact: true }),
			'FeaturesRoadmap must render its own heading, not just the shell',
		).toBeVisible({ timeout: 30_000 })
	})

	// REQ-UI-001 and REQ-UI-002 are two halves of one join, and the join key is
	// the thing worth testing end-to-end: `SettingsSection::getID()` decides
	// where the entry appears in the admin navigation, and
	// `AdminSettings::getSection()` decides which section the form is rendered
	// into. If those two strings disagree, Nextcloud still renders the nav
	// entry and still has a form — they simply never meet, and every unit test
	// of either half passes. Clicking the nav entry and finding the form is the
	// only assertion that fails when they drift apart.
	//
	// @e2e admin-ui::section-appears-in-admin-navigation
	// @e2e admin-ui::admin-opens-the-apps-settings-section
	// @e2e admin-ui::section-join-key
	test('the admin section is listed, opens, and renders the app form', async ({
		page,
	}) => {
		await loginToNextcloud(page, ADMIN_USER, ADMIN_PASS)

		await page.goto('/index.php/settings/admin')
		// The section registered by SettingsSection::getID() === 'portaliq'.
		//
		// BOTH SETTINGS SHELLS, because this app declares NC 32 to 34 and the
		// two halves of that range do not render the same one. Up to NC 33 the
		// settings page is server-rendered and its container is
		// `#app-navigation` (nextcloud/server, apps/settings/templates/settings/
		// frame.php@stable32 and @stable33, line 13/10: `<div id="app-navigation">`).
		// NC 34 replaced that template with a Vue app — the same file@stable34 is
		// just `<div id="settings-app"></div>` — and apps/settings/src/views/
		// SettingsNavigation.vue renders the list through `<NcAppNavigation>`,
		// whose root carries `id="app-navigation-vue"`. Scoping to the pre-NC34
		// id alone made this test report "SettingsSection must contribute an
		// entry to the admin navigation" on stable34, which was never true: the
		// section was registered and listed, in a container the selector could
		// not see. The scoping is kept rather than dropped because being IN the
		// navigation is half of what this test exists to prove.
		const sectionLink = page
			.locator(
				'#app-navigation a[href*="/settings/admin/portaliq"], #app-navigation-vue a[href*="/settings/admin/portaliq"]',
			)
			.first()
		await expect(
			sectionLink,
			'SettingsSection must contribute an entry to the admin navigation',
		).toBeVisible({ timeout: 60_000 })

		await sectionLink.click()
		await expect(page).toHaveURL(/\/settings\/admin\/portaliq$/)

		// AdminSettings::getForm() renders templates/settings/admin.php, whose
		// mount host is #portaliq-settings. Reaching it from the NAV entry (as
		// opposed to navigating straight to the URL) is what proves the two
		// ids agree.
		await expect(
			page.locator('#portaliq-settings'),
			'AdminSettings::getSection() must return the same id SettingsSection::getID() does, or the form never renders inside the section',
		).toBeVisible({ timeout: 60_000 })
	})

	// ADR-006 requires `{app}_`-prefixed metrics, which for this app is
	// `portaliq_`. (The spec text used to name `app_template_info`, inherited
	// verbatim from the scaffold; `MetricsController::METRIC_PREFIX` was fixed
	// to `portaliq` precisely because the placeholder violated ADR-006, and its
	// docblock records that. The spec has been corrected to match the ADR.)
	//
	// @e2e observability::admin-scrapes-metrics
	test('an admin scrape returns Prometheus text with the info and health gauges', async () => {
		const admin = await newIdentity({ user: ADMIN_USER, pass: ADMIN_PASS })
		try {
			await assertCallerIs(admin, ADMIN_USER)

			const res = await admin.get(`${API_BASE}/metrics`)
			expect(res.status(), 'an admin scrape must succeed').toBe(200)
			expect(res.headers()['content-type']).toContain('text/plain')
			expect(res.headers()['content-type']).toContain('version=0.0.4')

			const body = await res.text()
			expect(body).toContain('portaliq_info{app="portaliq"')
			expect(body).toMatch(/^portaliq_health_status [01]$/m)
		} finally {
			await admin.dispose()
		}
	})

	// The negative half. `metrics#index` carries no #[NoAdminRequired], so
	// Nextcloud's own admin gate must reject both a signed-in non-admin and an
	// anonymous caller — and, critically, must emit NO metric data in either
	// case. Both identities are checked, each on its own jar, each having first
	// proved who it is.
	//
	// @e2e observability::non-admin-scrape-attempt
	test('a non-admin and an anonymous scrape are refused and emit no metrics', async () => {
		const reader = await newIdentity({ user: E2E_USER, pass: E2E_PASS })
		const anon = await newIdentity('anonymous')
		try {
			await assertCallerIs(reader, E2E_USER)
			await assertCallerIs(anon, null)

			for (const [label, ctx] of [
				['non-admin', reader],
				['anonymous', anon],
			] as const) {
				const res = await ctx.get(`${API_BASE}/metrics`)
				expect(
					res.status(),
					`${label} must not be allowed to scrape metrics`,
				).not.toBe(200)
				const body = await res.text()
				expect(body, `${label} must receive no metric data`).not.toContain(
					'portaliq_info',
				)
				expect(body, `${label} must receive no metric data`).not.toContain(
					'portaliq_health_status',
				)
			}
		} finally {
			await reader.dispose()
			await anon.dispose()
		}
	})

	// `health#index` is #[PublicPage] + #[NoCSRFRequired] on purpose: the
	// probes that consume it (Kubernetes liveness, blackbox exporters) have no
	// credentials. Asserted from the ANONYMOUS jar, so a leaked admin cookie
	// cannot make a non-public endpoint look public.
	//
	// @e2e observability::dependencies-healthy
	test('the health endpoint is public and reports OpenRegister healthy', async () => {
		const anon = await newIdentity('anonymous')
		try {
			await assertCallerIs(anon, null)

			const res = await anon.get(`${API_BASE}/health`)
			expect(
				res.status(),
				'health must answer 200 when every dependency is present',
			).toBe(200)
			const body = await res.json()
			expect(body.status).toBe('ok')
			expect(body.app).toBe('portaliq')
			expect(body.dependencies?.openregister).toBe(true)
		} finally {
			await anon.dispose()
		}
	})

	// REQ-CFG-001 + REQ-CFG-004. `openregisters` IS the observable output of
	// `SettingsService::isOpenRegisterAvailable()` — there is no other surface
	// on which that probe's result is visible, so asserting it here is the
	// end-to-end form of REQ-CFG-004 rather than a restatement of REQ-CFG-001.
	//
	// The non-admin half asserts the SHIPPED contract, which is stricter than
	// the scaffold spec text used to claim: `SettingsController::index()`
	// strips the `register` binding for non-admins so the register UUID is not
	// handed to every authenticated user (unit-pinned by
	// `SettingsControllerTest::testIndexStripsRegisterForNonAdmin`). The spec
	// has been corrected to describe that.
	//
	// @e2e settings-management::admin-user-reads-settings
	// @e2e settings-management::non-admin-user-reads-settings
	// @e2e settings-management::probe-openregister-availability
	test('settings read: isAdmin reflects the caller, and register is admin-only', async () => {
		const admin = await newIdentity({ user: ADMIN_USER, pass: ADMIN_PASS })
		const reader = await newIdentity({ user: E2E_USER, pass: E2E_PASS })
		try {
			await assertCallerIs(admin, ADMIN_USER)
			await assertCallerIs(reader, E2E_USER)

			const adminRes = await admin.get(`${API_BASE}/settings`)
			expect(adminRes.status()).toBe(200)
			const adminBody = await adminRes.json()
			expect(
				adminBody.isAdmin,
				'the admin must be told they are an admin',
			).toBe(true)
			expect(adminBody).toHaveProperty('register')
			// REQ-CFG-004: OpenRegister is installed on the CI instance
			// (`additional-apps` pins it), so the probe must say so.
			expect(adminBody.openregisters).toBe(true)

			const readerRes = await reader.get(`${API_BASE}/settings`)
			expect(
				readerRes.status(),
				'any authenticated user may read settings',
			).toBe(200)
			const readerBody = await readerRes.json()
			expect(readerBody.isAdmin).toBe(false)
			expect(readerBody.openregisters).toBe(true)
			expect(
				Object.prototype.hasOwnProperty.call(readerBody, 'register'),
				'the register binding must not be exposed to a non-admin',
			).toBe(false)
		} finally {
			await admin.dispose()
			await reader.dispose()
		}
	})

	// REQ-CFG-002. Writes the ONE key in CONFIG_KEYS (`register`), asserts the
	// echoed config, then restores the original value so the instance is left
	// as it was found — the portal specs in this suite read the same register
	// binding.
	//
	// The unknown-key half is asserted in the SAME write, not a separate one:
	// `updateSettings()` iterates CONFIG_KEYS, so "unknown is ignored" and
	// "known is persisted" are two readings of one response, and splitting them
	// into two writes would let the second silently pass on the first's state.
	//
	// @e2e settings-management::admin-updates-a-known-setting
	// @e2e settings-management::payload-contains-an-unknown-key
	test('an admin write persists CONFIG_KEYS entries and silently ignores unknown keys', async () => {
		const admin = await newIdentity({ user: ADMIN_USER, pass: ADMIN_PASS })
		try {
			await assertCallerIs(admin, ADMIN_USER)

			const before = await (await admin.get(`${API_BASE}/settings`)).json()
			const original = before.register ?? ''
			const probe = `e2e-${Date.now()}`

			const res = await admin.post(`${API_BASE}/settings`, {
				data: {
					register: probe,
					thisKeyIsNotInConfigKeys: 'must-be-ignored',
				},
			})
			expect(res.status()).toBe(200)
			const body = await res.json()
			expect(body.success).toBe(true)
			expect(
				body.config?.register,
				'a CONFIG_KEYS entry must be persisted',
			).toBe(probe)
			expect(
				Object.prototype.hasOwnProperty.call(
					body.config ?? {},
					'thisKeyIsNotInConfigKeys',
				),
				'an unknown key must be ignored, not stored and not surfaced as an error',
			).toBe(false)

			// Read back through a fresh request so the assertion is about
			// PERSISTED state rather than the echo of the write.
			const after = await (await admin.get(`${API_BASE}/settings`)).json()
			expect(after.register).toBe(probe)

			await admin.post(`${API_BASE}/settings`, {
				data: { register: original },
			})
			const restored = await (await admin.get(`${API_BASE}/settings`)).json()
			expect(
				restored.register,
				'the instance must be left as it was found',
			).toBe(original)
		} finally {
			await admin.dispose()
		}
	})

	// The write endpoints carry no #[NoAdminRequired], so the framework gate
	// must refuse a signed-in non-admin. Both verbs are checked: the canonical
	// PUT and the retained legacy POST alias declare their auth posture
	// INDEPENDENTLY, because Nextcloud's SecurityMiddleware evaluates the
	// attributes of the DISPATCHED method only — `create()` delegating to
	// `update()` does not inherit `update()`'s posture.
	//
	// The refusal is asserted as "not 200 AND nothing was written", not on a
	// specific status code: a rejected write that still mutated state would be
	// the actual defect, and a status assertion alone cannot see it.
	//
	// @e2e settings-management::non-admin-tries-to-update
	test('a non-admin cannot write settings over either verb, and nothing changes', async () => {
		const admin = await newIdentity({ user: ADMIN_USER, pass: ADMIN_PASS })
		const reader = await newIdentity({ user: E2E_USER, pass: E2E_PASS })
		try {
			await assertCallerIs(admin, ADMIN_USER)
			await assertCallerIs(reader, E2E_USER)

			const before =
				(await (await admin.get(`${API_BASE}/settings`)).json()).register
				?? ''

			const attempted = `non-admin-must-not-write-${Date.now()}`
			const post = await reader.post(`${API_BASE}/settings`, {
				data: { register: attempted },
			})
			expect(
				post.status(),
				'POST /api/settings must be refused for a non-admin',
			).not.toBe(200)
			const put = await reader.put(`${API_BASE}/settings`, {
				data: { register: attempted },
			})
			expect(
				put.status(),
				'PUT /api/settings must be refused for a non-admin',
			).not.toBe(200)

			const after =
				(await (await admin.get(`${API_BASE}/settings`)).json()).register
				?? ''
			expect(after, 'a refused write must not have mutated app config').toBe(
				before,
			)
		} finally {
			await admin.dispose()
			await reader.dispose()
		}
	})

	// REQ-CFG-003. `settings#load` calls `loadConfiguration(force: true)`,
	// which is the same forced import ci-seed.sh performs — so this asserts the
	// endpoint is callable AT ANY TIME (not only on install), which is the part
	// of the requirement no unit test can reach.
	//
	// HTTP 200 is necessary but not sufficient here: the controller answers 200
	// with `{"success": false, …}` when the import itself failed, which is
	// exactly the shape ci-seed.sh has to defend against. The body is what is
	// asserted.
	//
	// @e2e settings-management::admin-triggers-re-import-while-openregister-is-available
	test('an admin can re-trigger the configuration import at any time', async () => {
		const admin = await newIdentity({ user: ADMIN_USER, pass: ADMIN_PASS })
		try {
			await assertCallerIs(admin, ADMIN_USER)

			const res = await admin.post(`${API_BASE}/settings/load`, { data: {} })
			expect(res.status()).toBe(200)
			const body = await res.json()
			expect(
				body.success,
				'settings#load answers 200 even when the import failed; the body is the verdict',
			).toBe(true)
		} finally {
			await admin.dispose()
		}
	})
})
