#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2026 Conduction B.V.
# SPDX-License-Identifier: EUPL-1.2
#
# Provision Portaliq on a freshly installed Nextcloud for the shared
# `E2E Tests (Playwright)` CI job.
#
# Wired up as the workflow's `playwright-seed-command`. That step runs AFTER
# `php -S` is up and with cwd set to the Nextcloud server root, so this is
# invoked as:
#
#     playwright-seed-command: 'bash apps/portaliq/tests/e2e/ci-seed.sh'
#
# cwd being the server root is load-bearing twice over: `php occ` is directly
# runnable from here, and the app lives at `apps/portaliq`.
#
# WHAT A FRESH INSTANCE IS MISSING, AND WHY EACH GAP IS SILENT
# ------------------------------------------------------------
#  1. THE REGISTER. `occ app:enable portaliq` runs the `InitializeSettings`
#     post-migration repair step, which calls
#     `SettingsService::loadConfiguration(force: false)`. Two things make that
#     unreliable as the sole fresh-install path and BOTH fail silently: a
#     repair step historically ran with no user session (OpenRegister's RBAC
#     then denies the import outright — `User 'Anonymous' does not have
#     permission to 'create' objects in schema '…'`), and the non-forced path
#     is version-guarded, so it can record "already current" without having
#     applied anything. `InitializeSettings::run()` catches `\Throwable` and
#     downgrades it to `$output->warning(...)`, so `occ app:enable portaliq`
#     exits 0 either way. The app enables, the SPA boots, and the register
#     simply is not there.
#  2. DEV-LOGIN. Every portal spec mints its bearer through
#     `POST /portal/api/session/dev-login`, which
#     `SessionController::isDevLoginEnabled()` gates behind system `debug` OR
#     the app flag `portaliq/dev_login_enabled`. Neither is set on a fresh
#     instance, so the endpoint 404s and every spec fails on its own
#     "dev-login must be enabled" assertion. We set the DEDICATED app flag
#     rather than system `debug`, because blanket debug mode changes error
#     rendering and log verbosity across the whole instance and would make the
#     runner behave unlike any environment the app is developed against.
#  3. A NON-ADMIN NEXTCLOUD USER. `tests/e2e/app-shell-and-admin.spec.ts`
#     asserts that a signed-in NON-ADMIN is refused by `/api/metrics` and by
#     both settings write verbs, and that `/api/settings` strips the register
#     binding for them. A fresh instance has exactly one user — `admin` — so
#     without this the only available negative identity is "anonymous", which
#     proves a strictly weaker thing: it cannot tell an admin-only endpoint
#     apart from a merely login-only one. The user is created here and then
#     VERIFIED to exist AND to not be in the admin group, because a user that
#     silently failed to be created reads, at the HTTP layer, exactly like one
#     that was correctly refused.
#  4. THE SIGNING SECRET. `PortalSessionService` refuses to mint a session
#     without a dedicated `portaliq/jwt_signing_secret`; `dev-login` then
#     returns HTTP 503 `not_configured`. That secret is generated by the SAME
#     repair step as (1), so it is verified here rather than assumed — and
#     deliberately NOT generated here, because generating it would hide a
#     broken install path behind a green suite.
#
# So this script provisions each of those EXPLICITLY and then VERIFIES it. A
# failed provision becomes ONE loud step failure here instead of a dozen
# misleading spec failures later.
#
# It is idempotent: the import is idempotent server-side, `occ config:app:set`
# is a write-through, and re-running only re-verifies.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

# ── Target resolution ────────────────────────────────────────────────────────
# The shared workflow's "Seed test data" step exports BASE_URL / NEXTCLOUD_URL /
# NC_BASE_URL / ADMIN_USER / ADMIN_PASSWORD / NC_ADMIN_USER / NC_ADMIN_PASS.
# Accept all of them, and fall back to the CI runner's own
# `php -S 0.0.0.0:8080` only when actually running on CI.
#
# On a developer box `localhost:8080` is the SHARED dev container, and this
# script performs ADMIN WRITES and flips an auth-related app flag — it must
# never do that to somebody else's environment. Off CI, an unset target is a
# hard error.
BASE="${PLAYWRIGHT_BASE_URL:-${BASE_URL:-${NEXTCLOUD_URL:-${NC_BASE_URL:-}}}}"
if [ -z "$BASE" ]; then
	if [ "${GITHUB_ACTIONS:-}" = "true" ] || [ "${CI:-}" = "true" ]; then
		BASE="http://localhost:8080"
	else
		echo "ERROR: no base URL set. Export PLAYWRIGHT_BASE_URL or BASE_URL." >&2
		echo "       Refusing to default to http://localhost:8080 outside CI —" >&2
		echo "       that is the SHARED dev container and this script writes to it," >&2
		echo "       including enabling the debug-gated portal dev-login endpoint." >&2
		exit 1
	fi
fi
BASE="${BASE%/}"

USER_NAME="${ADMIN_USER:-${NC_ADMIN_USER:-admin}}"
USER_PASS="${ADMIN_PASSWORD:-${NC_ADMIN_PASS:-admin}}"

echo "[ci-seed] target:  ${BASE}"
echo "[ci-seed] app dir: ${APP_DIR}"

# `occ` lives at the Nextcloud server root, which is this step's cwd. Resolve
# it explicitly so a future change to the workflow's cwd fails loudly here
# rather than silently skipping the flag below.
OCC=""
if [ -f "./occ" ]; then
	OCC="php ./occ"
elif [ -f "${APP_DIR}/../../occ" ]; then
	OCC="php ${APP_DIR}/../../occ"
fi

# ── 1. Enable the dedicated dev-login flag ───────────────────────────────────
# See note (2) in the header. `config:app:set` is preferred over
# `config:system:set debug --value=true` on purpose.
if [ -n "$OCC" ]; then
	# THE THEME APP, because this app no longer ships design tokens.
	#
	# `css/themes/` was deleted when the VNG token set moved to `nldesign`, so
	# `nldesign` is now a RUNTIME DEPENDENCY of the public portal rather than a
	# nice-to-have. Without it the site renders with no `--utrecht-*` at all:
	# every rule falls back to the value baked into its own declaration, so the
	# markup is intact, the text is readable, nothing 404s — and the portal is
	# unstyled. `site-design-system.spec.ts` asserts the token layer is present
	# precisely so that state fails loudly instead of being noticed by eye.
	#
	# Enabled BEST-EFFORT and reported either way: a runner without the app
	# checked out should say so here, once, rather than surface as a wall of
	# style assertions in the suite.
	if $OCC app:enable nldesign >/dev/null 2>&1; then
		echo "[ci-seed] nldesign enabled (design tokens available)"
	else
		echo "[ci-seed] WARNING: could not enable nldesign — the portal will render"
		echo "[ci-seed]          UNSTYLED and the design-system specs will fail."
		echo "[ci-seed]          portaliq ships no tokens of its own since css/themes/ was removed."
	fi

	echo "[ci-seed] enabling portaliq/dev_login_enabled"
	$OCC config:app:set portaliq dev_login_enabled --value=yes
	echo "[ci-seed] dev_login_enabled = $($OCC config:app:get portaliq dev_login_enabled 2>/dev/null || echo '<unset>')"
else
	echo "::error::Could not locate Nextcloud's occ (cwd=$(pwd))."
	echo "::error::The seed step must run with cwd = the Nextcloud server root."
	exit 1
fi

# ── 1b. Provision the NON-ADMIN identity the negative assertions need ────────
# See note (3) in the header. Kept in sync BY NAME with the constants in
# tests/e2e/app-shell-and-admin.spec.ts (E2E_USER / E2E_PASS) — a bash script
# cannot export into a TypeScript module, so the coupling is a comment on both
# sides and this script verifies the result rather than assuming it.
#
# The password is 19 characters on purpose: Nextcloud's default password policy
# rejects anything under 10 and `occ user:add` reports that as a non-obvious
# failure, so a shorter one would create nothing and leave the specs failing on
# a 401 that accuses the endpoint.
E2E_USER="${PORTALIQ_E2E_USER:-e2e-reader}"
E2E_PASS="${PORTALIQ_E2E_PASS:-e2e-reader-pw-2026}"

if $OCC user:info "$E2E_USER" >/dev/null 2>&1; then
	echo "[ci-seed] non-admin user ${E2E_USER} already exists"
else
	echo "[ci-seed] creating non-admin user ${E2E_USER}"
	# `|| true`: re-running the seed on an instance where the user exists but
	# `user:info` was unavailable must not abort under `set -e`. The
	# verification below is the gate, not this command's exit code.
	OC_PASS="$E2E_PASS" $OCC user:add --password-from-env --display-name="E2E Reader" "$E2E_USER" || true
fi

# VERIFY — two separate claims, because "the user exists" and "the user is not
# an admin" fail in different ways and only the second one makes the negative
# assertions meaningful. A user accidentally added to `admin` would turn every
# "must be refused" assertion green for the wrong reason.
E2E_INFO="$(mktemp)"
$OCC user:info "$E2E_USER" --output=json >"$E2E_INFO" 2>/dev/null || echo '{}' >"$E2E_INFO"
python3 - "$E2E_INFO" "$E2E_USER" <<'PY'
import json, sys
path, uid = sys.argv[1], sys.argv[2]
try:
    info = json.loads(open(path).read() or '{}')
except json.JSONDecodeError:
    info = {}
if not info or info.get('user_id') != uid:
    print(f'::error::Non-admin e2e user {uid!r} was not created (occ user:info returned {info!r}).')
    print('::error::app-shell-and-admin.spec.ts would then fail on a 401 that accuses the endpoint '
          'rather than the seed. Check the password policy (minimum 10 characters).')
    sys.exit(1)
groups = [str(g).lower() for g in (info.get('groups') or [])]
if 'admin' in groups:
    print(f'::error::e2e user {uid!r} is in the admin group ({groups}).')
    print('::error::Every "a non-admin must be refused" assertion would then pass because the '
          'request WAS refused-proof — i.e. for the wrong reason.')
    sys.exit(1)
print(f'[ci-seed] non-admin user OK: {uid} groups={groups}')
PY

# ── 2. Import the Portaliq configuration ─────────────────────────────────────
# `appinfo/routes.php` registers `settings#load` at POST /api/settings/load,
# which calls `SettingsService::loadConfiguration(force: true)` — precisely the
# forced import the repair step cannot be relied upon to perform.
# `SettingsController::load()` carries no `#[NoAdminRequired]`, so HTTP Basic
# as admin is required.
#
# `OCS-APIRequest: true` is load-bearing, not decoration: Nextcloud's
# `Request::passesCSRFCheck()` short-circuits to true on that header (the
# strict-cookie precondition is satisfied because a Basic-auth request carries
# no session cookie at all). Without it this POST is rejected as a CSRF
# failure.
IMPORT_URL="${BASE}/index.php/apps/portaliq/api/settings/load"
echo "[ci-seed] POST ${IMPORT_URL} (forced import)"

IMPORT_BODY="$(mktemp)"
IMPORT_CODE="$(
	curl -sS -o "$IMPORT_BODY" -w '%{http_code}' \
		-u "${USER_NAME}:${USER_PASS}" \
		-X POST \
		-H 'Content-Type: application/json' \
		-H 'OCS-APIRequest: true' \
		--data '{}' \
		"$IMPORT_URL" || echo 000
)"

echo "[ci-seed] settings#load HTTP ${IMPORT_CODE}"
head -c 2000 "$IMPORT_BODY"; echo

# HTTP 200 is necessary but NOT sufficient: `SettingsController::load()`
# returns `{"success": false, "message": "..."}` with a 200 when the import
# itself failed. Treat anything that is not an explicit success as a reason to
# try the generic importer below, and let the verification step decide.
IMPORT_OK=0
if [ "$IMPORT_CODE" = "200" ] && grep -q '"success":[[:space:]]*true' "$IMPORT_BODY"; then
	IMPORT_OK=1
	echo "[ci-seed] portaliq settings#load reported success."
else
	echo "[ci-seed] portaliq settings#load did not report success; falling back to the OpenRegister importer."
fi

# ── 2b. Fallback: OpenRegister's generic configuration importer ──────────────
# Independent of portaliq's own controller wiring. Admin-only. It reads the
# upload under the literal form key `file`; a raw JSON request body is NOT one
# of its accepted shapes.
if [ "$IMPORT_OK" != "1" ]; then
	REGISTER_JSON="${APP_DIR}/lib/Settings/portaliq_register.json"
	if [ ! -f "$REGISTER_JSON" ]; then
		echo "::error::portaliq_register.json not found at ${REGISTER_JSON}."
		exit 1
	fi

	OR_URL="${BASE}/index.php/apps/openregister/api/configurations/import"
	echo "[ci-seed] POST ${OR_URL} (file=portaliq_register.json, force=true)"
	OR_BODY="$(mktemp)"
	OR_CODE="$(
		curl -sS -o "$OR_BODY" -w '%{http_code}' \
			-u "${USER_NAME}:${USER_PASS}" \
			-X POST \
			-H 'OCS-APIRequest: true' \
			-F "file=@${REGISTER_JSON}" \
			-F 'force=true' \
			-F 'appId=portaliq' \
			"$OR_URL" || echo 000
	)"
	echo "[ci-seed] configurations/import HTTP ${OR_CODE}"
	head -c 2000 "$OR_BODY"; echo
fi

# ── 3. Verify the register and schemas are actually there ────────────────────
# An import reporting success is not the same as the register existing.
#
# The register slug is `portaliq`: `portaliq_register.json` declares no
# `components.registers` block at all, so the register is created by
# OpenRegister's `ImportHandler::autoCreateRegisterIfApplication()`, which fires
# on `x-openregister.type == "application"` and takes the slug from
# `x-openregister.app`. The schema slugs below are read verbatim out of
# `components.schemas[*].slug` in that same file — NOT kebab-cased or guessed;
# OpenRegister resolves a URL segment by `LOWER(slug)`, so a structural
# mismatch (an underscore, a prefix) is fatal while a casing difference is not.
#
# The HTTP status is captured and checked separately from the payload on
# purpose: an endpoint that 404s or redirects to a login form yields an empty
# slug set, which is indistinguishable from "the import produced nothing" if
# you only look at the parsed list. A wrong lookup manufactures an absence for
# free, so the two are reported as different errors.
verify() {
	python3 - "$1" "$2" "$3" <<'PY'
import json, sys
path, kind, code = sys.argv[1], sys.argv[2], sys.argv[3]
required = {
    'registers': ['portaliq'],
    'schemas': [
        'portalAccount', 'portalSession', 'exampleDocument', 'portalMessage',
        'portalSubmission', 'portalAuditEntry', 'portalNotification',
        'portalOidcState', 'portalPage',
    ],
}[kind]
with open(path) as fh:
    raw = fh.read()
if code != '200':
    print(f'::error::OpenRegister {kind} endpoint returned HTTP {code}, so the '
          f'slug list below proves nothing about the import. First 500 bytes:')
    print(raw[:500])
    sys.exit(1)
try:
    body = json.loads(raw)
except json.JSONDecodeError:
    print(f'::error::{kind} endpoint did not return JSON (HTTP 200). First 500 bytes:')
    print(raw[:500])
    sys.exit(1)
items = body if isinstance(body, list) else body.get('results', [])
slugs = {str(i.get('slug')).lower() for i in items if isinstance(i, dict) and i.get('slug')}
missing = [s for s in required if s.lower() not in slugs]
print(f'[ci-seed] {kind} present: {sorted(slugs)}')
if missing:
    print(f'::error::Portaliq {kind} missing after import: {missing}')
    print('::error::The portal SPA has no data surface without them and every spec would '
          'fail on a selector timeout that accuses the UI.')
    sys.exit(1)
print(f'[ci-seed] {kind} OK ({len(required)} required slugs present)')
PY
}

REG_BODY="$(mktemp)"
REG_CODE="$(curl -sS -u "${USER_NAME}:${USER_PASS}" -H 'OCS-APIRequest: true' \
	-o "$REG_BODY" -w '%{http_code}' \
	"${BASE}/index.php/apps/openregister/api/registers?_limit=300" || echo 000)"
verify "$REG_BODY" registers "$REG_CODE"

SCH_BODY="$(mktemp)"
SCH_CODE="$(curl -sS -u "${USER_NAME}:${USER_PASS}" -H 'OCS-APIRequest: true' \
	-o "$SCH_BODY" -w '%{http_code}' \
	"${BASE}/index.php/apps/openregister/api/schemas?_limit=1000" || echo 000)"
verify "$SCH_BODY" schemas "$SCH_CODE"

# ── 4. Verify the seeded portalPage objects landed ───────────────────────────
# Since `portal-page-provisioning`, `PortalContributionProvider` is CONFIG
# DRIVEN: it contributes nothing except what ACTIVE `portalPage` objects
# describe. The demo pages ship as seed objects in `portaliq_register.json`
# (`dev-citizen-intake`, audience citizen; `dev-supplier-demo`, audience
# supplier). If the seed-object half of the import is skipped while the schema
# half succeeds, the register verification above still passes, the SPA still
# boots — and every spec fails on an empty portal with no nav. Check the rows
# themselves.
PAGES_BODY="$(mktemp)"
PAGES_CODE="$(curl -sS -u "${USER_NAME}:${USER_PASS}" -H 'OCS-APIRequest: true' \
	-o "$PAGES_BODY" -w '%{http_code}' \
	"${BASE}/index.php/apps/openregister/api/objects/portaliq/portalPage?_limit=50" || echo 000)"
echo "[ci-seed] objects/portaliq/portalPage -> HTTP ${PAGES_CODE}"
python3 - "$PAGES_BODY" "$PAGES_CODE" <<'PY'
import json, sys
path, code = sys.argv[1], sys.argv[2]
with open(path) as fh:
    raw = fh.read()
if code != '200':
    print(f'::error::portalPage collection returned HTTP {code}; the portal contributes nothing '
          f'without it. First 500 bytes:')
    print(raw[:500])
    sys.exit(1)
body = json.loads(raw)
items = body if isinstance(body, list) else body.get('results', [])
active = {}
for row in items:
    if isinstance(row, dict) and row.get('status') == 'active':
        active.setdefault(row.get('audience'), 0)
        active[row['audience']] += 1
print(f'[ci-seed] active portalPage audiences: {active}')
missing = [a for a in ('supplier', 'citizen') if a not in active]
if missing:
    print(f'::error::No ACTIVE portalPage object for audience(s) {missing}.')
    print('::error::PortalContributionProvider is config-driven — with no matching portalPage row '
          'a logged-in subject sees an empty portal, and every spec fails on a selector timeout '
          'that reads like broken UI rather than missing seed data.')
    sys.exit(1)
print('[ci-seed] portalPage seed objects OK')
PY

# ── 5. Verify the auth edge can actually mint a session ──────────────────────
# `PortalSessionService` refuses to sign without a dedicated
# `portaliq/jwt_signing_secret` (generated by the InitializeSettings repair
# step). Deliberately verified, NOT generated: generating it here would paper
# over a broken install path.
SECRET_LEN="$($OCC config:app:get portaliq jwt_signing_secret 2>/dev/null | tr -d '\n' | wc -c || echo 0)"
echo "[ci-seed] jwt_signing_secret length: ${SECRET_LEN}"
if [ "$SECRET_LEN" -lt 32 ] 2>/dev/null; then
	echo "::error::portaliq/jwt_signing_secret is missing or too short (${SECRET_LEN} chars)."
	echo "::error::lib/Repair/InitializeSettings.php generates it on install/upgrade; if it is absent"
	echo "::error::that repair step did not run. dev-login would return 503 not_configured and every"
	echo "::error::spec would fail on its 'dev-login must be enabled' assertion — which names the"
	echo "::error::wrong cause."
	exit 1
fi

# Probe the endpoint the specs actually depend on, so its failure has a name
# here rather than eleven names later.
DEV_BODY="$(mktemp)"
DEV_CODE="$(
	curl -sS -o "$DEV_BODY" -w '%{http_code}' \
		-X POST \
		-H 'Content-Type: application/json' \
		-H 'OCS-APIRequest: true' \
		--data '{"subjectRef":"ci-seed-probe","audience":"supplier","organisation":"e2e-org"}' \
		"${BASE}/index.php/apps/portaliq/portal/api/session/dev-login" || echo 000
)"
echo "[ci-seed] dev-login probe -> HTTP ${DEV_CODE}"
head -c 500 "$DEV_BODY"; echo
if [ "$DEV_CODE" != "200" ] || ! grep -q '"token"' "$DEV_BODY"; then
	echo "::error::POST /portal/api/session/dev-login did not mint a token (HTTP ${DEV_CODE})."
	echo "::error::404 => the dev_login_enabled app flag did not take (step 1)."
	echo "::error::503 => no jwt_signing_secret (step 5)."
	echo "::error::Every portal spec mints its bearer here, so all of them would fail on the same"
	echo "::error::assertion with no indication of which of those two causes it was."
	exit 1
fi

# ── 6. Warm the SPA, and GATE on the portal bundle serving as JavaScript ─────
# The shared workflow serves Nextcloud with `php -S 0.0.0.0:8080`. It sets
# PHP_CLI_SERVER_WORKERS=8, but the first hit still pays a cold opcache and the
# first parse of a multi-megabyte webpack bundle; warming it here puts that
# cost in the environment-preparation step rather than inside an assertion
# timeout that would then have to keep drifting upward.
for path in \
	"/index.php/apps/portaliq/portal" \
	"/index.php/apps/portaliq/portal/api/session" \
	"/index.php/apps/openregister/api/registers?_limit=1"
do
	code="$(curl -sS -o /dev/null -w '%{http_code}' -u "${USER_NAME}:${USER_PASS}" \
		-H 'OCS-APIRequest: true' "${BASE}${path}" || echo 000)"
	echo "[ci-seed] warm ${path} -> ${code}"
done

# Pull the portal bundle once so it is in the page cache — and then GATE on it.
#
# Portaliq ships TWO bundles from two webpack configs: `portaliq-main.js` (the
# internal Vue admin SPA, webpack.config.js) and `portaliq-portal.js` (the
# public React portal, webpack.portal.js). EVERY e2e spec drives the PORTAL, so
# the portal bundle is the one that matters here. `npm run build` builds both;
# `npm run build:admin` alone deletes the portal bundle (see the
# `output.clean` note in webpack.config.js).
#
# Do NOT hardcode the URL. Nextcloud serves an app's assets from whichever apps
# directory it was installed into — `/apps/portaliq/js/…` on the CI runner,
# `/custom_apps/portaliq/js/…` in the docker dev images — and asking for the
# wrong one does not 404. It returns HTTP 200 with `text/html`: the Nextcloud
# error page, served through index.php. A status-code check therefore reports
# success while fetching a 40 KB HTML page instead of a multi-MB bundle.
#
# Read the real src out of the rendered portal page instead, and verify the
# response is actually JavaScript.
PORTAL_HTML="$(mktemp)"
curl -sS "${BASE}/index.php/apps/portaliq/portal" -o "$PORTAL_HTML" || true

# `|| true` is load-bearing: grep exits 1 when it matches nothing, and under
# `set -euo pipefail` that aborts the script right here — so the case the gate
# below exists to explain (no bundle) would die with a bare non-zero exit and
# none of the diagnosis.
BUNDLE_SRC="$(grep -oE 'src="[^"]*portaliq-portal[^"]*"' "$PORTAL_HTML" \
	| head -1 | sed 's/^src="//; s/"$//' || true)"

if [ -n "$BUNDLE_SRC" ]; then
	BUNDLE_INFO="$(curl -sS -o /dev/null \
		-w '%{http_code} %{content_type} %{size_download}' \
		"${BASE}${BUNDLE_SRC}" || echo '000 - 0')"
	echo "[ci-seed] warm bundle ${BUNDLE_SRC} -> ${BUNDLE_INFO}"
else
	echo "[ci-seed] could not locate the portal bundle src in the rendered portal page."
	BUNDLE_INFO=""
fi

# On CI this is a GATE, not a warm-up.
#
# The single most likely way this job "succeeds" dishonestly is by passing
# without ever loading the SPA — and the environment hides it well: when the
# bundle is absent, Nextcloud does not 404. It serves its HTML error page with
# HTTP 200 and Content-Type text/html, so a build producing nothing looks, to
# every status-code check in the pipeline, exactly like success.
#
# Note that this gate reads the SERVED response, not the file on disk, and it
# is placed at the very end so that a run which reaches the specs has provably
# been able to fetch real JavaScript for the portal.
if [ "${GITHUB_ACTIONS:-}" = "true" ] || [ "${CI:-}" = "true" ]; then
	case "$BUNDLE_INFO" in
		*javascript*)
			echo "[ci-seed] portal bundle verified as JavaScript."
			;;
		*)
			echo "::error::The Portaliq PORTAL bundle did not serve as JavaScript (got: ${BUNDLE_INFO:-<not found>})."
			echo "::error::The React portal cannot mount, so every spec would fail on a selector timeout with a misleading cause."
			echo "::error::Check the 'Build app frontend' step — 'npm run build' must run build:portal as well as build:admin,"
			echo "::error::and a missing bundle returns HTTP 200 text/html, not 404."
			exit 1
			;;
	esac
fi

# ---------------------------------------------------------------------------
# CMS fixtures for the site-renderer specs (site-content / site-multisite /
# site-security).
#
# Without these, every one of those specs fails — and fails MISLEADINGLY: with
# no portal seeded, PortalResolver correctly resolves nothing and the content
# API correctly 404s, so the specs report "expected 200, got 404" as though the
# API were broken. It is behaving exactly as specified; there is simply no
# content. That is the failure this block prevents.
#
# Note the two specs that would pass ANYWAY on an empty instance — S7 (unknown
# host) and S7b (unknown site slug) both assert a 404. They are the reason the
# seed matters: a suite where the negative cases pass vacuously and the
# positive ones are absent reads as "mostly working".
echo "[ci-seed] seeding CMS fixtures..."
if NC_URL="$BASE" NC_AUTH="${USER_NAME}:${USER_PASS}" bash "$(dirname "$0")/fixtures/seed-cms.sh"; then
	echo "[ci-seed] CMS fixtures seeded."
else
	echo "::error::CMS seeding failed. The site-renderer specs would fail with"
	echo "::error::'expected 200, got 404' — which is the API behaving CORRECTLY"
	echo "::error::against an empty instance, not a defect in it."
	exit 1
fi

echo "[ci-seed] done."
